stages:
  - infrastructure-update

environment:
  stage: infrastructure-update
  script:
    - export
  

pulumi:
  stage: infrastructure-update
  before_script:
    - chmod +x ./scripts/*.sh
    - ./scripts/setup.sh
  script:
    - ./scripts/run-pulumi.sh
  artifacts:
    paths:
    - pulumi-log.txt
    expire_in: 1 week
  only:
    refs:
      - master

pulumi-preview:
  stage: infrastructure-update
  before_script:
    - chmod +x ./scripts/*.sh
    - ./scripts/setup.sh
  script:
    - ./scripts/pulumi-preview.sh
  only:
    - merge_requests
