language: node_js
os: linux
dist: xenial
branches:
  only:
  - master
install:
  # Install Node.js 10.16.3
  - nvm install v10.16.3
  # Install Pulumi
  - curl -fsSL https://get.pulumi.com/ | bash
  - export PATH="$HOME/.pulumi/bin:$PATH"
before_script:
  - chmod +x ./scripts/*.sh
  - ./scripts/setup.sh
jobs:
  include:
    - stage: pulumi-preview
      script: ./scripts/pulumi-preview.sh
      if: branch != master
    - stage: pulumi-up
      script: echo "I will run for master branches only!"
      if: branch = master
