# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.18-alpine

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Mark scripts as executable
          command: chmod +x ./scripts/*.sh

  pulumi-preview:
    run:
      name: Run pulumi preview
      command: ./scripts/pulumi-preview.sh
  pulumi-up:
    run:
      name: Run pulumi up
      command: |
        echo "I will run on master branch merges only!"
        # Uncomment the following line to actually run pulumi up for your use.
        # ./scripts/run-pulumi.sh

workflows:
  version: 2
  workflow:
    jobs:
      - build
<<<<<<< HEAD
      - pulumi-preview:
          requires:
            - build
          when: << pipeline.git.branch >> != "master"
      - pulumi-up:
          requires:
            - build
          when: << pipeline.git.branch >> == "master"
=======
      - pulumi:
          requires:
            - build
          filters:
            branches:
              only: master
>>>>>>> ec0d089... Add CircleCI configuration
